spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: TU_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

server:
  port: 8080
